name: Update Age in README

on:
  schedule:
    - cron: '0 0 6 6 *'     # (your birthday)
    - cron: '0 0 1 1 *'     # Optional: every Jan 1 as a fallback
  workflow_dispatch:        # Allows manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate age and update README
        run: |
          BIRTHDATE="1998-06-06"
          TODAY=$(date +%Y-%m-%d)
          AGE=$(( ( $(date -d "$TODAY" +%s) - $(date -d "$BIRTHDATE" +%s) ) / 31556952 ))

          echo "Current Age: $AGE"

          sed -i "s/{age}/$AGE/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git commit -am "Update age in README" && git push)
